### ISSUE TITLE
Compare whattheflux outputs with fluxes computed by e.g. SoilFluxPro

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/fluxfinder#40]
This would be a useful—perhaps crucial— addition to the manuscript @wilsonsj100 .

**Comment by wilsonsj100** [comment]
Agreed - this would be interesting. I typically just take the soilfluxpro fluxes and don't recalculate, but after seeing SWH fluxes it would probably be helpful to do so. Due to the soggy ground last year sometimes the fluxes were wonky and it would be helpful to recalculate and compare.
