### ISSUE TITLE
ffi_read_LGR915 incompatible with .txt file format

### ISSUE THREAD

**Issue by Qepanna** [COMPASS-DOE/fluxfinder#57]
I tried importing a raw file from my LGR915 instrument using the function ffi_read_LGR915, but the function seems to be incompatible with .txt file format. I tried converting the file to .csv, but that did not help.

```
> dat <- ffi_read_LGR915("UGGA.txt")
Warning message:
All formats failed to parse. No formats found. 

> dat <- ffi_read_LGR915("UGGA.csv")
Warning message:
All formats failed to parse. No formats found. 
```

[UGGA.txt](https://github.com/COMPASS-DOE/fluxfinder/files/15412960/UGGA.txt)

**Comment by bpbond** [comment]
Hi @Qepanna - thanks for trying fluxfinder! Appreciate you opening this issue. @wilsonsj100 and I are happy to add this new format to the package. Just to check, the file you attached is exactly as downloaded from the instrument, i.e. it comes with a ".txt" extension?

**Comment by Qepanna** [comment]
Hi @bpbond and @wilsonsj100, yes this is the raw file I get from my instrument.

**Comment by bpbond** [comment]
I just looked at the data files and it looks like the LGR writes out either MM/DD/YYYY (U.S.) or DD/MM/YYYY (rest of the world). Argh, that's a _terrible_ design decision. 🤦

**Comment by Qepanna** [comment]
Haha yes, very frustrating :)

By the way, I have two different LGR915 (with different date formats, of course) and I just noticed that they have slithly different outputs. One is the "micro" ultra-portable GGA, and the other is just a plain uGGA.

Also, be aware of the "PGP MESSAGE" at the end of the file.

I also just noticed that there was a little issue with the file I gave you previously, so I am uploading new ones here.

[gga_2021-10-04_f0001.txt](https://github.com/COMPASS-DOE/fluxfinder/files/15434284/gga_2021-10-04_f0001.txt)
[micro_2021-10-04_f0001.txt](https://github.com/COMPASS-DOE/fluxfinder/files/15434294/micro_2021-10-04_f0001.txt)

**Comment by bpbond** [comment]
OK, thank you -- that's very helpful!

The "PGP MESSAGE" is bizarre; you're sure that's in the raw file that's downloaded? I ask only because it doesn't exist in our test files.

I will change `ffi_read_LGR915()` to be able to handle these formats; more soon.

**Comment by Qepanna** [comment]
Very bizarre indeed! I have always used these (unzipped) .txt files from these instruments, and the PGP thing is always there.

**Comment by bpbond** [comment]
OK, we can handle that. Thanks.

**Comment by bpbond** [comment]
@Qepanna I have pushed a new version that handles your files; could you please test it?

Install following the instructions in the [README file](https://github.com/COMPASS-DOE/fluxfinder/blob/main/README.md).

**Comment by Qepanna** [comment]
Thank you, it works with both formats now.
