### ISSUE TITLE
Comparison with smart chamber fluxes

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/fluxfinder#60]
@robertapeixoto [suggested](https://github.com/COMPASS-DOE/fluxfinder/pull/59#issuecomment-2195109956) comparing Smart Chamber-computed fluxes with flux finder fluxes. Great idea!

![comparison](https://github.com/COMPASS-DOE/fluxfinder/assets/1956468/001ad7be-d219-4b73-9b94-2ce1663b256f)

Hmm...looks like we're off by 10x?!? 😕 

I'm off for next 10 days, but logging this here for later.

**Comment by robertapeixoto** [comment]
In this case, we should double-check the unity transformation in fluxfinder. Another possibility is that Licor's calculation has a correction for water vapor. I tried to match our data with smart chamber using TIMESTAMP. I noticed that the code that transforms the .json file to .csv does not get a label (the unique ID from the smart chamber). Would it be easy to include it? The Licor-SoilFLuxPro unique ID is under the Li8200 label. We can return to these points after Jul 10th. I found other issues with volume calculation in the SoilFLuxPro that I want to spend more time checking. I had a few different collars offset but the same total volume!

**Comment by wilsonsj100** [comment]
I agree with Roberta that it would definitely be helpful if the soilflux ID put in for the smart chamber was carried over.

**Comment by bpbond** [comment]
@wilsonsj100 @robertapeixoto I did some more investigating this morning, and the graph above is WRONG — I had messed things up. Here's the current comparison between Smart Chamber fluxes and `fluxfinder` fluxes:

![comparison](https://github.com/user-attachments/assets/138f7955-0ad0-4e70-8e10-cc2554dbd88b)

Solid line is 1:1, dashed blue line is linear fit.

>Licor's calculation has a correction for water vapor.

We're using the concentrations corrected for water vapor, so I think that's OK.

**Comment by robertapeixoto** [comment]
[celebrate]     Bittencourt Peixoto, Roberta reacted to your message:
________________________________
From: Ben Bond-Lamberty ***@***.***>
Sent: Tuesday, July 16, 2024 2:59:09 PM
To: COMPASS-DOE/fluxfinder ***@***.***>
Cc: Bittencourt Peixoto, Roberta ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [COMPASS-DOE/fluxfinder] Comparison with smart chamber fluxes (Issue #60)


@wilsonsj100<https://github.com/wilsonsj100> @robertapeixoto<https://github.com/robertapeixoto> I did some more investigating this morning, and the graph above is WRONG — I had messed things up. Here's the current comparison between Smart Chamber fluxes and fluxfinder fluxes:

comparison.png (view on web)<https://github.com/user-attachments/assets/138f7955-0ad0-4e70-8e10-cc2554dbd88b>

Solid line is 1:1, dashed blue line is linear fit.

Licor's calculation has a correction for water vapor.

We're using the concentrations corrected for water vapor, so I think that's OK.
