### ISSUE TITLE
Import data for a LI-850 

### ISSUE THREAD

**Issue by wilsonsj100** [COMPASS-DOE/fluxfinder#61]
Can we add an ffi_read_LI850 function to the read options or can ffi_read_LI8x0 work (saw this in the code). Example file attached @nickdward 
[Aquaria_Exp1_CO2Flux_070124.txt](https://github.com/user-attachments/files/16181532/Aquaria_Exp1_CO2Flux_070124.txt)

**Comment by bpbond** [comment]
Yup, will do. Just checking -- a `.txt` file extension is correct? Or was that manually changed after downloading the data?

**Comment by nickdward** [comment]
The .txt file is the raw data that the LI-850 saves/exports. It doesn’t save anything as .dat

**Comment by wilsonsj100** [comment]
[like]  Wilson, Stephanie reacted to your message:
________________________________
