### ISSUE TITLE
URL Checker

### ISSUE THREAD

**Issue by wilsonsj100** [COMPASS-DOE/fluxfinder#79]
@bpbond I ran URL Checker and got the following errors. Working on checking them to see if the links work for me. 

urlchecker::url_check()

✖ Error: README.md:43:19 Error: Operation timed out after 60004 milliseconds with 0 bytes received
* Older [LGR 915](https://new.abb.com/products/measurement-products/analytical/laser-gas-analyzers/laser-analyzers/lgr-icos-portable-analyzers) analyzers
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
✖ Error: man/ffi_read_LIsmartchamber.Rd:23:15 404: Not Found
See also \url{https://www.licor.com/env/products/soil-flux/smart-chamber}.
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
✖ Error: README.md:41:30 404: Not Found
* The [LI-COR Smart Chamber](https://www.licor.com/env/products/soil-flux/smart-chamber)
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
✖ Error: README.md:42:37 404: Not Found
* [LI-COR 78xx Trace Gas Analyzers](https://www.licor.com/env/products/trace-gas/), including the LI-7810 and LI-7820
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
✖ Error: README.md:46:23 404: Not Found
* The [LI-COR LI-850](https://www.licor.com/env/support/LI-850/topics/specifications.html)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by wilsonsj100** [comment]
Yeah... do you have any thoughts on what to do about this? These links work for me when I put them in on google chrome....

**Comment by bpbond** [comment]
Hang on, let me try

**Comment by wilsonsj100** [comment]
Okay sounds good - thank you!

**Comment by bpbond** [comment]
I get the same thing.

But, see [here](https://stackoverflow.com/questions/66078248/invalid-url-in-cran-checks) -- I think we can safely ignore these notes.

**Comment by wilsonsj100** [comment]
Hmmm even though the ones it flagged were not DOI URLs??

**Comment by bpbond** [comment]
I don't know! But as you say above, the links are clearly valid, and people in that thread I linked say their submissions went through OK. But 🤷 

Reading the CRAN policies here https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Specifying-URLs I don't _see_ a problem.

**Comment by wilsonsj100** [comment]
Agreed - okay I’m moving on! Thank you
